version: '3.7'

volumes:
  todolist:
    name: todolist
    driver: local

networks:
  api-network:
    driver: bridge

services:
  nginx:
    working_dir: /application
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../.:/application
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.crt:/etc/nginx/ssl/server.pem
      - ./nginx/cert.key:/etc/nginx/ssl/server-key.pem
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - api-network

  node1:
    working_dir: /application
    volumes:
      - ./../.:/application
    command: bash -c "cd /application/src && npm i && npm run start:dev"
    depends_on:
      - mongodb
    networks:
      - api-network

  node2:
    working_dir: /application
    volumes:
      - ./../.:/application
    command: bash -c "cd /application/src && npm i && npm run start:dev"
    depends_on:
      - mongodb
    networks:
      - api-network

  node3:
    working_dir: /application
    volumes:
      - ./../.:/application
    command: bash -c "cd /application/src && npm i && npm run start:dev"
    depends_on:
      - mongodb
    networks:
      - api-network

  mongodb:
    volumes:
      - todolist:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - api-network

  redis:
    ports:
      - 6379:6379
    restart: always
    networks:
      - api-network

  redislabs:
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - redis
    networks:
      - api-network
